spring.application.name=SmartMarket
server.port=8081

jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCBzaWduaW5n
jwt.expiration=8358707612

logging.level.org.springframework.security=DEBUG
logging.level.com.SmartMarket.security=TRACE

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

telegram.bot.token=
telegram.bot.username=
